version: '3'
services:
    php-fpm:
        build:
            context: ./services/php-fpm
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        tty: true
        volumes:
            - ./src:/var/www
        environment:
            - COMPOSER_HOME=/home/user/.composer
        ports:
            - "8080:8080"